namespace tests
	@suite
	class NavigationModelTests extends tests.BaseTestSuite

		protected override function setUp()
			super.setUp()

			m.SUT = SomeModel()
		end function

		'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
		@describe("Tests for SomeModel public methods")
		'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

		@it("globalMockExample1")
		function _()
			m.stubCall(getManifestValue, function(key) : return "stubCall hardcoded title" : end function)
			m.SUT.globalMockExample()
			m.assertEqual(m.SUT.appTitle, "stubCall hardcoded title")
		end function

		@it("globalMockExample2")
		@params("stubCall created title")
		function _(manifestValue as string)
			m.stubCall(getManifestValue, manifestValue)
			m.SUT.globalMockExample()
			m.assertEqual(m.SUT.appTitle, manifestValue)
		end function

	end class
end namespace
